#!/usr/bin/env bash
# Generate AGENTS.md by concatenating skills/*/SKILL.md files.
#
# - Strips YAML frontmatter (the block between the first two `---` lines).
# - Demotes ATX headings by one level (# -> ##, ## -> ###, ...) so that the
#   H1 of each skill becomes a section under AGENTS.md's own H1.
# - Leaves headings inside fenced code blocks (```...```) untouched.
#
# Run from anywhere; paths resolve relative to the repo root.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

out="AGENTS.md"
skills=(skills/*/SKILL.md)

if [ ${#skills[@]} -eq 0 ] || [ ! -e "${skills[0]}" ]; then
  echo "error: no skill files found under skills/*/SKILL.md" >&2
  exit 1
fi

# Write intro block.
cat > "$out" <<'EOF'
# Twake Guidelines — Agent Rules

Linagora Twake / Cozy coding conventions for AI coding agents. This file aggregates every skill so that agents reading a single rules file (like [OpenCode](https://opencode.ai) via `AGENTS.md`) pick up all rules at once.

> **Do not edit this file by hand.** It is generated from `skills/*/SKILL.md` by `scripts/gen-agents.sh`. Edit the skill files, then regenerate.
>
> **Claude Code users:** do not load this file directly. Install the plugin instead (`/plugin install twake-guidelines@twake-guidelines`) — skills are auto-triggered per context, which keeps each prompt lean.
EOF

# Append each skill, demoted and stripped of frontmatter, with a `---` separator.
for skill in "${skills[@]}"; do
  {
    echo ""
    echo "---"
    echo ""
  } >> "$out"

  awk '
    BEGIN { fm_state = 0; in_fence = 0 }   # fm_state: 0=pre, 1=inside, 2=post
    {
      if (fm_state < 2 && $0 == "---") {
        if (fm_state == 0) { fm_state = 1; next }
        if (fm_state == 1) { fm_state = 2; next }
      }
      if (fm_state == 1) next
      if (fm_state == 0) { fm_state = 2 }  # no frontmatter, treat all as body

      if ($0 ~ /^```/) { in_fence = !in_fence; print; next }
      if (!in_fence && $0 ~ /^#+[[:space:]]/) { print "#" $0; next }
      print
    }
  ' "$skill" >> "$out"
done

count=${#skills[@]}
echo "✓ Wrote $out from $count skill file$([ $count -ne 1 ] && echo s)"
